# -*- coding: utf-8 -*-
"""Paises_DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qUwcP5gLom_mtgHCecZfjGmnkoUd-fDt

<h1>Inicialização</h1>
<p>Criando a base do projeto e verificando se esta tudo certo
"""

import pandas as pd # type: ignore
print(f'versão do pandas', pd.__version__) #verificar a versão do pandas e se esta corretamente instalado
paises = { #criando o dicionario do data frame
    'Nome': ['Brasil', 'Alemanha', 'Japao', 'Canada', 'Australia', 'Africa do Sul'],
    'Continente': ['America', 'Europa', 'Asia', 'America', 'Oceania', 'Africa'],
    'PopulacaoMilhoes': [213, 83, 125, 38, 26, 60],
    'Idioma': ['Portugues', 'Alemao', 'Japones', 'ingles', 'ingles', 'ingles'],
    'IDH': [0.760, 0.947, 0.915, 0.929, 0.944, 0.699] #dados do bing copilot
}
print('checando quantos elementos tem em cada coluna')#garantir que  não ha nenhuma informação faltando ou bug
print(f'coluna nome', len(paises['Nome']))
print(f'coluna continente', len(paises['Continente']))
print(f'coluna população', len(paises['PopulacaoMilhoes']))
print(f'coluna idioma', len(paises['Idioma']))
print(f'coluna IDH', len(paises['IDH']))
colunas = ['Nome', 'Continente', 'PopulacaoMilhoes', 'Idioma', 'IDH'] #noemando as colunas do data frame

"""<h1>Questão 1</h1>
<p>Apresente em tela (output) toda a base de dados.

"""

print("Data frame aqui")
paisesDF = pd.DataFrame(data = paises, columns = colunas)#data recebe o dicionario, columns recebe a lista com o nome das colunas
print(paisesDF)

"""<h1>Questão 2 </h1>
<p>Apresente o tamanho do seu dataframe (quantas colunas x linhas)

"""

print("Proporção")
print(paisesDF.shape)#retorna a proporção do data frame linhas X colunas

"""<h1>Questão 3</h1>
<p>Acesse a linha (x) e apresente em tela todas as características do item
"""

print("Retorna somente a linha 3")
print(paisesDF.iloc[2])#retorna a linha 3

"""<h1>Questão 4</h1>
<p>Verifique se o dataframe está vazio
"""

print("verifica se esta vazio")
print(f"data frame esta vazio?", paisesDF.empty)#verifica se esta vazio
empetyDF = pd.DataFrame()#cria um data frame vazio
print(f"data frame vazio esta vazio?", empetyDF.empty)#verifica se esta vazio

"""<h1>Questão 5</h1>
<p>Apresente em tela os 5 primeiros registros da base de dados
"""

LINHAS_EXIBIR = 5 #constante para alterar o valor de linhas desejado
print(f"exibi apenas as {LINHAS_EXIBIR} primeiras linhas")
print(paisesDF.head())#deixe o head sem parametro que ele exibe os 5 primeiros. passe o paramenetro para definir a quantias

"""<h1>Questão 6</h1>
<p>Exclua um item (linha) de sua base de dados<p>
"""

INDEX_EXCLUIR = 2 #constante para definir o indice que sera excluido
print(F"Exclui o item do index {INDEX_EXCLUIR}")
print(paisesDF.drop(index=INDEX_EXCLUIR, inplace=False))#exclui a linha 3. inplace true rescreve a variavel. false apenas retornar o df sem esse valor

"""<h1>Questão 7</h1>
<p> Adicione um item (linha) na sua base de dados
"""

print("adiciona nova linha")
novaLinha = pd.DataFrame([ { #cria um novo data frame com as linhas que devem ser adicionadas
    'Nome' : 'Estados Unidos',
    'Continente' :'america',
    'PopulacaoMilhoes' : 333, #dados do bing copilot
    'Idioma' : 'ingles',
    'IDH' : 0.902
}])
paisesDF = pd.concat([paisesDF, novaLinha], ignore_index=True) # concatenas ambos os data frames. Ignore_index = true pra que seja adicionado ao final do primeiro data frame
print(paisesDF)

"""<h1>Questão 8</h1>
<p>Transponha a coluna para a linha em sua base de dados
"""

print("Trocar linhas e colunas")
print(paisesDF.transpose())#linhas virão colunas e colunas viram linhas

"""<h1>Questão 9</h1>
<p>Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados.
"""

print('exibir apenas a primeira e a segunda coluna')
print(paisesDF.iloc[:, :2])#pega as colunas 0 e 1. primeiro parametro indica as linhas o segundo as colunas